config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'welcome#index'
  get '/welcome' => 'welcome#index'

  devise_for :users

  resources :users
  resources :trails do
    resources :reviews
  end

  get 'welcome/:id' => 'welcome#show', as: "trail_name"

 get 'profiles/' => 'profiles#index'
 get 'profiles/new' => 'profiles#new', as: 'new'
 post '/profiles' => 'profiles#create'
 get '/profiles/:id' => 'profiles#show', as: 'show'
 get '/profiles/:id/edit' => 'profiles#edit', as: 'edit'
 patch '/profiles/:id' => 'profiles#update', as: 'update'
 delete '/profiles/:id', to: 'profiles#destroy', as: 'destroy'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  # attr_accessible :rate, :dimension
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true



end

app/models/rating.rb
class Rating < ActiveRecord::Base

belongs_to :trail
belongs_to :user

 validates :trail, presence: true
 validates :user, presence: true
 validates :value, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 5 }
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :trail
end

app/models/trail.rb
class Trail < ActiveRecord::Base
  ratyrate_rateable "rating"
  has_many :reviews
  has_many :photos
  has_many :users, through: :reviews


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :photos
  has_many :trails, through: :reviews
  has_many :profiles
  ratyrate_rater

end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :username])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

before_action :authenticate_user!
before_action :get_profile, only: [:edit, :update]
before_action :set_profile, only: [ :edit, :update, :destroy]
before_action :review_owner, only: [:destroy, :edit, :update]


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.where(user_id: current_user.id)
    @trails = Trail.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit

  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    @profile.save

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profiles_path, notice: 'Photo was successfully uploaded.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_path(@profile), notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :description, :image)
    end

    def review_owner
      unless current_user.id == @profile.user_id
        flash[:notice] = 'Error'
        redirect_to trail_name_path(@trails)
      end
    end

    def get_profile
   @profile = current_user.profile
end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_filter :authenticate_user!
before_action :find_post
before_action :find_review, only: [:destroy, :edit, :update, :review_owner]
before_action :review_owner, only: [:destroy, :edit, :update]

def index
  @reviews = Review.all
  @trails = Trail.all
end


def destroy
  @reviews.destroy
  redirect_to trail_name_path(@trails)
end


def new
  @reviews = Review.new
end

def create
  # <input type="text" name="text"
  @review = @trails.reviews.new({
    text: params[:review][:text]
  })
  @review.user_id = current_user.id
  @review.save

  if @review.save
    redirect_to trail_name_path(@trails)
  else
    render 'new'
  end

end

def update
  if @reviews.update(params[:review].permit(:text))
    redirect_to trail_name_path(@trails)
  else
    render 'edit'
  end
end

private

def find_post
  @trails = Trail.find(params[:trail_id])
end

def find_review
  @reviews = @trails.reviews.find(params[:id])
end

def review_owner
  unless current_user.id == @reviews.user_id
    flash[:notice] = 'Error'
    redirect_to trail_name_path(@trails)
  end
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @trails = Trail.all
end


  def show
    @trails = Trail.find(params[:id])
    @reviews = Review.where(trail_id: @trails).order("created_at DESC")
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/trail_helper.rb
module TrailHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, html: { multipart: true } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <div id="form">
  <div class="wrapper">
       <%= f.file_field :image %>
       <% if f.object.image? %>
         <%= image_tag f.object.image_url(:thumb) %><br>

         <%= f.label :remove_image %>
         <%= f.check_box :remove_image %>
         <% end %>
       </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit 'Upload', :class => 'btn btn-default' %>

</form>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/welcome">Home</a></li>
  <li role="presentation" class="active"><a href="/profiles">Photos</a></li>


<% if user_signed_in? %>
      Signed in as <%= current_user.email %>.
    <li role="presentation"> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li role="presentation"> <%= link_to 'Register', new_user_registration_path %><li>  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>


</ul>


<p id="notice"><%= notice %></p>

<h1><%= current_user.username %>'s Gallery</h1>
<Center><%= link_to 'Upload Photos', new_path %></center>



    <% @profiles.each do |profile| %>
    <div id="instagramstuffs">
        <%= image_tag profile.image_url(:thumb) %><br>
        <%= link_to 'Info', show_path(profile) %> |
        <%= link_to 'Delete', destroy_path(profile), method: :delete, data: { confirm: 'Are you sure?' } %><br>
  </div>
    <% end %>

app/views/profiles/new.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="/welcome">Home</a></li>
  <li role="presentation"><a href="/profiles">Photos</a></li>


<% if user_signed_in? %>
      Signed in as <%= current_user.email %>.
    <li role="presentation"> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li role="presentation"> <%= link_to 'Register', new_user_registration_path %><li>  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>
</ul>

<div id="newprofile">
<h2>New Image</h2>

<%= render 'form' %><br>

<%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="/welcome">Home</a></li>
  <li role="presentation"><a href="/profiles" class="active">Photos</a></li>


<% if user_signed_in? %>
      Signed in as <%= current_user.email %>.
    <li role="presentation"> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li role="presentation"> <%= link_to 'Register', new_user_registration_path %><li>  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>


</ul>


<p id="notice"><%= notice %></p>


  <strong>Image:</strong>
  <%= image_tag @profiles.image_url(:thumb) %>
</div>

<br>
<p>
  <strong>Name:</strong>
  <%= @profiles.name %></br>
</p>

<p>
  <strong>Description:</strong><br>
  <%= @profiles.description %>
</p>




<%= link_to 'Back', profiles_path %>
</div>

app/views/reviews/_form.html.erb
<%= form_for ([@trails, @trails.reviews.build]) do |f| %>
  <%= f.text_field :text %><br>
   Your rating:<%= rating_for @trails, 'rating',  disable_after_rate: false  %>
  <%= f.submit 'Submit', :class => 'btn btn-default' %>
<% end %>

app/views/reviews/_reviews.html.erb
<% @reviews.each do |review| %>

  <p class="review"><%= review.text %></p>
  <p><%= review.user.username %> </p>
  <%= link_to "Delete comment",[review.trail, review], method: :delete %>
<% end %>

app/views/welcome/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="/welcome">Home</a></li>
  <li role="presentation"><a href="/profiles">Photos</a></li>


<% if user_signed_in? %>
      Signed in as <%= current_user.email %>.
    <li role="presentation"> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li role="presentation"> <%= link_to 'Register', new_user_registration_path %><li>  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>


</ul>




  <div class="titlepage">
    <div class="titletext">Ascend la</div>

    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="https://player.vimeo.com/video/130699654?autoplay=1&loop=1&background=1&color=ffffff&portrait=0" width="1000" height="567" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen>
    </iframe>

    </div>
</div>




<div class="context">
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Hikes
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">

<% @trails.each do |trail| %>

  <div class="col-md-6">
    <dl class="dl-horizontal"><%= trail.location %>
      <dt>
    <%= link_to trail.name, trail_name_path(trail.id) %>
  </dt>
  </dl>
</div>
<% end %>
</div>
   </div>
 </div>





<i class="glyphicon glyphicon-copyright-mark"> </i> Kayli Nishime<br>
Filmed by Tim Eddy: The Land of the Long White Cloud - New Zealand<br>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %><br>
<div>

app/views/welcome/show.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="/welcome">Home</a></li>
  <li role="presentation"><a href="/profiles">Photos</a></li>

<% if user_signed_in? %>
      Signed in as <%= current_user.email %>.
    <li role="presentation"> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li role="presentation"> <%= link_to 'Register', new_user_registration_path %><li>  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>
</ul>


<div id="trails">
<h1><%= @trails.name %></h1>
<h6><%= @trails.location %> | Level: <%= @trails.level %> | <%= @trails.distance %></h6>
</div>

<div class="row">

  <div class="col-md-6">
    <div id="googlemaps">
    <style>
      #map {
        width: 400px;
        height: 400px;
      }
    </style>
        <h4>Directions</h4>
        <br>
        <div id="map"></div>
      </div>

  </div>


  <div class="col-md-6">
    <h4>Reviews</h4>
    Average Rating: <%= rating_for @trails, 'rating' %>
<br>
  <%= render 'reviews/form' %>

    <%= render 'reviews/reviews' %>
  </div>
</div>






  <script>
    function initMap() {
var myLatLng = {lat: <%= @trails.lat %>, lng: <%=@trails.lng %>};

var map = new google.maps.Map(document.getElementById('map'), {
  zoom: 15,
  center: myLatLng
});

var marker = new google.maps.Marker({
  position: myLatLng,
  map: map,
  title: 'Hello World!'
});
}
    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnA6Vq2_4VZQH_M8zAjK9QoYNyvcO8ri8&callback=initMap">
    </script>
  </div>